export const PLATFORM_OPTIONS = [
  { value: 'amiga', label: 'Amiga' },
  { value: 'android', label: 'Android' },
  { value: 'arcade', label: 'Arcade' },
  { value: 'c64', label: 'Commodore C64/128/MAX' },
  { value: 'dc', label: 'Dreamcast' },
  { value: 'dos', label: 'DOS' },
  { value: 'fc', label: 'Family Computer' },
  { value: 'gb', label: 'Game Boy' },
  { value: 'gbc', label: 'Game Boy Color' },
  { value: 'gba', label: 'Game Boy Advance' },
  { value: 'ios', label: 'iOS' },
  { value: 'mac', label: 'Mac' },
  { value: 'msx', label: 'MSX' },
  { value: 'msx2', label: 'MSX2' },
  { value: 'ngage', label: 'N-Gage' },
  { value: 'ngcd', label: 'Neo Geo CD' },
  { value: 'ngp', label: 'Neo Geo Pocket' },
  { value: 'ngpc', label: 'Neo Geo Pocket Color' },
  { value: 'n64', label: 'Nintendo 64' },
  { value: 'nds', label: 'Nintendo DS' },
  { value: 'dsi', label: 'Nintendo DSi' },
  { value: '3ds', label: 'Nintendo 3DS' },
  { value: 'nes', label: 'Nintendo Entertainment System' },
  { value: 'gc', label: 'Nintendo GameCube' },
  { value: 'switch', label: 'Nintendo Switch' },
  { value: 'win', label: 'PC (Microsoft Windows)' },
  { value: 'pc98', label: 'PC-9800 Series' },
  { value: 'pcfx', label: 'PC-FX' },
  { value: 'ps1', label: 'PlayStation' },
  { value: 'ps2', label: 'PlayStation 2' },
  { value: 'ps3', label: 'PlayStation 3' },
  { value: 'ps4', label: 'PlayStation 4' },
  { value: 'ps5', label: 'PlayStation 5' },
  { value: 'psp', label: 'PlayStation Portable' },
  { value: 'psvita', label: 'PlayStation Vita' },
  { value: 'sat', label: 'Satellaview' },
  { value: 'scd', label: 'Sega CD' },
  { value: 'gg', label: 'Sega Game Gear' },
  { value: 'master', label: 'Sega Master System/Mark III' },
  { value: 'md', label: 'Sega Mega Drive/Genesis' },
  { value: 'saturn', label: 'Sega Saturn' },
  { value: 'x68000', label: 'Sharp X68000' },
  { value: 'sfc', label: 'Super Famicom' },
  { value: 'snes', label: 'Super Nintendo Entertainment System' },
  { value: 'pce', label: 'TurboGrafx-16/PC Engine' },
  { value: 'pcecd', label: 'Turbografx-16/PC Engine CD' },
  { value: 'virtual', label: 'Virtual Boy' },
  { value: 'wii', label: 'Wii' },
  { value: 'wiiu', label: 'Wii U' },
  { value: 'ws', label: 'WonderSwan' },
  { value: 'wsc', label: 'WonderSwan Color' },
  { value: 'xbox', label: 'Xbox' },
  { value: 'xbox360', label: 'Xbox 360' },
  { value: 'zeebo', label: 'Zeebo' },
]
